### ISSUE TITLE
Repo Structure

### ISSUE THREAD

**Issue by bstone** [adelphimathcs/ProjectEuler-0001#1]
@MichaelVessia, that was fast! Nice solution. What do you think about putting different solutions in different folders? Maybe create a folder `JavaSolutions/` and use `git mv` to place your solution there? You don't have to do it that way, but something would be nice. You might even want to place a `README.md` file in the folder commenting on how to use the program or maybe about the speed (which I imagine is instant).

**Comment by MichaelVessia** [comment]
@b-stone, I had thoughts of putting my name or some other identifier in my solution's filename, so others don't feel like they shouldn't upload their own.  Calling the solutions PE####.\* kind of feels like you are claiming it is THE solution.  What do you think?

**Comment by MattMatero** [comment]
The approach we are currently using is great for solutions done in different languages but once we have multiple doing the same problem with the same language it could lead to confusion. Maybe adding a convention for PEXXXX-initials (i.e. PE0001-MM) might make it more personal for those submitting and avoids the "i own this problem" feeling mike mentioned.

**Comment by bstone** [comment]
GitHub tracks the history, so authorship is not an issue. I think we should put solutions into folders. For example, ruby scripts go in `Ruby/` and java in `Java/`. This would allow people to submit there own versions in each language.  The folders would also allow for `README.md` files for comments and what not. As to file names, I am ok with whatever.

**Comment by MichaelVessia** [comment]
Sure thing. We should add that to each repo's `README.md` and retroactively make those directories before that becomes too large of a task to handle.  I'll be sure to do that moving forward as well.

**Comment by MichaelVessia** [comment]
I created directories in all of the current repos.  

I'm going to close this here since I don't think the issue belongs on this repo anyway.
